### ISSUE TITLE
eccodes dependency is not correctly installed when using uv for development

### ISSUE THREAD

**Issue by mrmorawski** [PyPSA/atlite#506]
### Version Checks (indicate both or one)

- [x] I have confirmed this bug exists on the lastest [release](https://github.com/pypsa/atlite/releases) of atlite.

- [x] I have confirmed this bug exists on the current [`master`](https://github.com/pypsa/atlite/tree/master) branch of atlite.

### Issue Description

Since [v 0.4.1] atlite uses `grib` to download data from CDS by default. This requires the `cdfgrib` backend for `xarray`. This in turn requires the EcCodes library to be present on the system.

This is not well documented, and results in failed downloads, and the test suite failing by default, without an explicit error message.

### Reproducible Example

```python
git clone https://github.com/PyPSA/atlite
cd atlite
uv sync --extra dev
uv run pytest test/ -v
```

Fails with:
```
ValueError: unrecognized engine 'cfgrib' must be one of your download engines: ['netcdf4', 'h5netcdf', 'scipy', 'pydap', 'store'].
```

### Expected Behavior

tests pass

### Installed Versions

<details>
appdirs==1.4.4
apsw==3.43.0.0
argcomplete==3.1.4
asttokens==2.4.1
async-timeout==4.0.3
attrs==23.2.0
Babel==2.10.3
bcc==0.29.1
bcrypt==3.2.2
beautifulsoup4==4.12.3
blinker==1.7.0
Brlapi==0.8.5
Brotli==1.1.0
certifi==2023.11.17
chardet==5.2.0
click==8.1.6
cloud-init==25.3
colorama==0.4.6
command-not-found==0.3
configobj==5.0.8
contourpy==1.0.7
cryptography==41.0.7
css-parser==1.0.10
cssselect==1.2.0
cupshelpers==1.0
cycler==0.11.0
dbus-python==1.3.2
decorator==5.1.1
defer==1.0.6
distro==1.9.0
distro-info==1.7+build1
dnspython==2.6.1
duplicity==2.1.4
executing==2.0.1
fasteners==0.18
feedparser==6.0.10
fonttools==4.46.0
fs==2.4.16
html2text==2024.2.26
html5-parser==0.4.12
html5lib==1.1
httplib2==0.20.4
idna==3.6
ifaddr==0.2.0
ipython==8.20.0
jedi==0.19.1
jeepney==0.8.0
Jinja2==3.1.2
jsonpatch==1.32
jsonpointer==2.0
jsonschema==4.10.3
kiwisolver==0.0.0
language-selector==0.1
launchpadlib==1.11.0
lazr.restfulclient==0.14.6
lazr.uri==1.0.6
libevdev==0.5
louis==3.29.0
lxml==5.2.1
lz4==4.0.2+dfsg
Mako==1.3.2.dev0
Markdown==3.5.2
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.6.3
matplotlib-inline==0.1.6
mdurl==0.1.2
mechanize==0.4.9
meson==1.3.2
monotonic==1.6
mpmath==0.0.0
msgpack==1.0.3
netaddr==0.8.0
netifaces==0.11.0
numpy==1.26.4
oauthlib==3.2.2
olefile==0.46
packaging==24.0
paramiko==2.12.0
parso==0.8.3
pexpect==4.9.0
pillow==10.2.0
pipx==1.4.3
platformdirs==4.2.0
prompt-toolkit==3.0.43
psutil==5.9.8
ptyprocess==0.7.0
pure-eval==0.0.0
py7zr==0.11.3+dfsg
pycairo==1.25.1
pychm==0.8.6
pycryptodomex==3.20.0
pycups==2.0.1
Pygments==2.17.2
PyGObject==3.48.2
PyJWT==2.7.0
PyNaCl==1.5.0
pyparsing==3.1.1
PyQt6==6.6.1
PyQt6-sip==13.6.0
PyQt6-WebEngine==6.6.0
pyrsistent==0.20.0
pyserial==3.5
python-apt==2.7.7+ubuntu5.2
python-dateutil==2.8.2
python-debian==0.1.49+ubuntu2
pytz==2024.1
pyudev==0.24.0
pyxdg==0.28
PyYAML==6.0.1
regex==2022.10.31
repoze.lru==0.7
requests==2.31.0
rich==13.7.1
rofication==1.2.2
Routes==2.5.1
SciPy==1.11.4
setuptools==68.1.2
sgmllib3k==1.0.0
six==1.16.0
soupsieve==2.5
stack-data==0.6.3
sympy==1.12
systemd-python==235
texttable==1.6.7
traitlets==5.5.0
types-aiofiles==23.2
types-aws-xray-sdk==2.12
types-beautifulsoup4==4.12
types-bleach==6.1
types-boltons==23.0
types-boto==2.49
types-braintree==4.24
types-cachetools==5.3
types-caldav==1.3
types-cffi==1.16
types-chevron==0.14
types-click-default-group==1.2
types-click-spinner==0.1
types-colorama==0.4
types-commonmark==0.9
types-console-menu==0.8
types-croniter==2.0
types-dateparser==1.1
types-decorator==5.1
types-Deprecated==1.2
types-dockerfile-parse==2.0
types-docopt==0.6
types-docutils==0.20
types-editdistance==0.6
types-entrypoints==0.4
types-ExifRead==3.0
types-first==2.0
types-flake8-2020==1.8
types-flake8-bugbear==23.9.16
types-flake8-builtins==2.2
types-flake8-docstrings==1.7
types-flake8-plugin-utils==1.3
types-flake8-rst-docstrings==0.3
types-flake8-simplify==0.21
types-flake8-typing-imports==1.15
types-Flask-Cors==4.0
types-Flask-Migrate==4.0
types-Flask-SocketIO==5.3
types-fpdf2==2.7.4
types-gdb==12.1
types-google-cloud-ndb==2.2
types-greenlet==3.0
types-hdbcli==2.18
types-html5lib==1.1
types-httplib2==0.22
types-humanfriendly==10.0
types-ibm-db==3.2
types-influxdb-client==1.38
types-inifile==0.4
types-JACK-Client==0.5
types-jmespath==1.0
types-jsonschema==4.19
types-keyboard==0.13
types-ldap3==2.9
types-libsass==0.22
types-Markdown==3.5
types-mock==5.1
types-mypy-extensions==1.0
types-mysqlclient==2.2
types-netaddr==0.9
types-oauthlib==3.2
types-openpyxl==3.1
types-opentracing==2.4
types-paho-mqtt==1.6
types-paramiko==3.3
types-parsimonious==0.10
types-passlib==1.7
types-passpy==1.0
types-peewee==3.17
types-pep8-naming==0.13
types-pexpect==4.8
types-pika-ts==1.3
types-Pillow==10.1
types-playsound==1.3
types-pluggy==1.2.0
types-polib==1.2
types-portpicker==1.6
types-protobuf==4.24
types-psutil==5.9
types-psycopg2==2.9
types-pyasn1==0.5
types-pyaudio==0.2
types-PyAutoGUI==0.9
types-pycocotools==2.0
types-pycurl==7.45.2
types-pyfarmhash==0.3
types-pyflakes==3.1
types-Pygments==2.16
types-pyinstaller==6.1
types-pyjks==20.0
types-PyMySQL==1.1
types-pynput==1.7
types-pyOpenSSL==23.3
types-pyRFC3339==1.1
types-PyScreeze==0.1.29
types-pyserial==3.5
types-pysftp==0.2
types-pytest-lazy-fixture==0.6
types-python-crontab==3.0
types-python-datemath==1.5
types-python-dateutil==2.8
types-python-gflags==3.1
types-python-jose==3.3
types-python-nmap==0.7
types-python-slugify==8.0
types-python-xlib==0.33
types-pytz==2023.3.post1
types-pywin32==306
types-pyxdg==0.28
types-PyYAML==6.0
types-qrcode==7.4
types-redis==4.6.0
types-regex==2023.10.3
types-requests==2.31
types-requests-oauthlib==1.3
types-retry==0.9
types-s2clientprotocol==5
types-seaborn==0.13
types-Send2Trash==1.8
types-setuptools==68.2
types-simplejson==3.19
types-singledispatch==4.1
types-six==1.16
types-slumber==0.7
types-stdlib-list==0.8
types-stripe==3.5
types-tabulate==0.9
types-tensorflow==2.12
types-toml==0.10
types-toposort==1.10
types-tqdm==4.66
types-translationstring==1.4
types-tree-sitter==0.20.1
types-tree-sitter-languages==1.8
types-ttkthemes==3.2
types-tzlocal==5.1
types-ujson==5.8
types-untangle==1.2
types-usersettings==1.1
types-uWSGI==2.0
types-vobject==0.9
types-waitress==2.1
types-WebOb==1.8
types-whatthepatch==1.0
types-workalendar==17.0
types-WTForms==3.1
types-xmltodict==0.13
types-zstd==1.5
types-zxcvbn==4.4
typing_extensions==4.10.0
ubuntu-drivers-common==0.0.0
ubuntu-pro-client==8001
ufoLib2==0.16.0
ufw==0.36.2
unattended-upgrades==0.1
unicodedata2==15.1.0
urllib3==2.0.7
usb-creator==0.3.16
userpath==1.9.1
wadllib==1.3.6
wcwidth==0.2.5
webencodings==0.5.1
WebOb==1.8.7
wheel==0.42.0
xdg==5
xkit==0.0.0
xxhash==0.0.0
zeroconf==0.131.0
</details>

**Comment by mrmorawski** [comment]
I see two ways to deal with this:
1. Prompt user to install eccodes, instructions can be found e.g. [here](https://gist.github.com/MHBalsmeier/a01ad4e07ecf467c90fad2ac7719844a)
2. Include `eccodellib` as a dependency. It installs the ecCodes binary and seems to be made for this usecase.

**Comment by euronion** [comment]
Thanks for reporting. I cannot reproduce the problem on my end.

`cfgrib` is an explicit dependency since `0.4.1` for the reason that you mention. It should get installed when installing `atlite`.
I tried it with a fresh install and do not encounter any issues. Did you make any modifications to your environment that might have removed the package forcefully?

**Comment by mrmorawski** [comment]
I tested everything on a clean Docker Ubuntu 26.04 image, and I managed to trace the issue down. It's something to do with `uv` as a dependency manager.

I ran the following example:

<details><summary>Example code</summary>
<p>
import atlite 

TIME = "2013-01-01"
X0 = -4.0
Y0 = 56.0
X1 = 1.5
Y1 = 61.0


c = atlite.Cutout(path="creation_ref", module="era5", bounds=(X0, Y0, X1, Y1), time=TIME)
c.prepare()
print("test successful")
</p>
</details> 

When installing  via `pip install atlite` or `uv add atlite` the example ran just fine.

However, when I cloned the `atlite` repository and then tried to install dependencies with `uv sync`, it fails, because `ecCodes` binary is not installed correctly. Reproducible with the following:

<details><summary>Steps to repoduce the issue when cloning</summary>
<p>


## Environment
- Python 3.14.4
- Ubuntu (resolute, May 2026)
- `uv` 0.11.9

## Steps to Reproduce

### Setup
```bash
docker run -ti --rm ubuntu /bin/bash
apt-get update && apt-get install -y curl git
curl -LsSf https://astral.sh/uv/install.sh | sh
source $HOME/.local/bin/env
```

### Test 1: Install from PyPI with `uv add` (✅ Works)
```bash
mkdir atlite-test && cd atlite-test
uv init
uv add atlite
export CDSAPI_URL=https://cds.climate.copernicus.eu/api
export CDSAPI_KEY=<your-key>
python test.py
# ✅ Result: test successful
```

Where `test.py` contains:
```python
import atlite 

TIME = "2013-01-01"
X0 = -4.0
Y0 = 56.0
X1 = 1.5
Y1 = 61.0


c = atlite.Cutout(path="creation_ref", module="era5", bounds=(X0, Y0, X1, Y1), time=TIME)
c.prepare()
print("test successful")
```

### Test 2: Clone from GitHub with `uv sync` (❌ Fails)
```bash
cd ..
git clone https://github.com/PyPSA/atlite
cd atlite
uv sync
export CDSAPI_URL=https://cds.climate.copernicus.eu/api
export CDSAPI_KEY=<your-key>
uv run python test.py
```

**Error Output:**
```
RuntimeWarning: Engine 'cfgrib' loading failed:
Cannot find the ecCodes library

ValueError: unrecognized engine 'cfgrib' must be one of your download engines: ['netcdf4', 'h5netcdf', 'scipy', 'store']. To install additional dependencies, see:
https://docs.xarray.dev/en/stable/user-guide/io.html
```

### Test 3: Clone from GitHub with `pip install` (✅ Works)
```bash
cd atlite
# Remove uv venv if it exists
rm -rf .venv
pip install . --break-system-packages
python test.py
# ✅ Result: test successful
```
</p>
</details> 

I went down the rabbit hole of verifying where the dependency resolution fails. It seems to only happen on Python 3.13 (as pinned in the current `atlite` `pyproject.toml`) when using uv. The MRE is:

```bash
docker run -ti --rm ubuntu /bin/bash

# then in the container
apt-get update && apt-get install -y curl
curl -LsSf https://astral.sh/uv/install.sh | sh
source $HOME/.local/bin/env

mkdir /tmp/repro && cd /tmp/repro
uv init --python 3.13
uv add cfgrib
uv run python -m eccodes selfcheck
# RuntimeError: Cannot find the ecCodes library
```

It works if you change 3.13 to 3.14 in the MRE.


I don't know whether the bug is in `uv` or `eccodes`. But the fix is pretty simple, just add `eccodeslib` (which installs the ecCodes binary) to `pyproject.toml`.

**Comment by mrmorawski** [comment]
And apologies for not providing a better MRE in the original issue description, I updated it to show that this happens only with uv and when cloning the repo.

**Comment by euronion** [comment]
Thanks for the update.
I can still not reproduce the issue, neither with `python==3.14.*` nor `python ==3.13.*` pinned in `pyproject.toml`.

Your MWE python script also yields a different error for me:
```
uv run python test.py                                                                                                                           7s
      Built atlite @ file:///home/<user>/Documents/GitHub/atlite-test/atlite
Uninstalled 1 package in 0.35ms
Installed 1 package in 0.50ms
Traceback (most recent call last):
  File "/home/<user>/Documents/GitHub/atlite-test/atlite/test.py", line 2, in <module>
    c = atlite.Cutout(name="test", module=["era5"], weather_data_config=dict())
TypeError: Cutout.__init__() missing 1 required positional argument: 'path'
```

**Comment by mrmorawski** [comment]
### Python 3.13 vs Python 3.14

You're right that the issue seems to be unrelated to the python version. The `eccodes selfcheck` MRE in my previous post works (fails on 3.13 and works on 3.14, output below). However, when running the atlite MRE, it fails even on 3.14.

<details><summary>just cfgrib with Python 3.13</summary>
<p>

```console
➜  ~ docker run -ti --rm ubuntu /bin/bash
root@87a41659985d:/# apt-get update && apt-get install -y curl && curl -LsSf https://astral.sh/uv/install.sh | sh

[truncated for brevity]

installing to /root/.local/bin
  uv
  uvx
everything's installed!

To add $HOME/.local/bin to your PATH, either restart your shell or run:

    source $HOME/.local/bin/env (sh, bash, zsh)
    source $HOME/.local/bin/env.fish (fish)
root@87a41659985d:/# source $HOME/.local/bin/env
root@87a41659985d:/# mkdir /tmp/repro && cd /tmp/repro && uv init --python 3.13 && uv add cfgrib && uv run python -m eccodes selfcheck
Initialized project `repro`
Using CPython 3.13.13
Creating virtual environment at: .venv
Resolved 10 packages in 1.26s
Prepared 8 packages in 7.61s
Installed 8 packages in 35ms
 + attrs==26.1.0
 + cffi==2.0.0
 + cfgrib==0.9.15.1
 + click==8.3.3
 + eccodes==2.47.0
 + findlibs==0.1.2
 + numpy==2.4.4
 + pycparser==3.0
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/tmp/repro/.venv/lib/python3.13/site-packages/eccodes/__init__.py", line 13, in <module>
    from .eccodes import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/repro/.venv/lib/python3.13/site-packages/eccodes/eccodes.py", line 12, in <module>
    from gribapi import (
    ...<8 lines>...
    )
  File "/tmp/repro/.venv/lib/python3.13/site-packages/gribapi/__init__.py", line 13, in <module>
    from .gribapi import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/repro/.venv/lib/python3.13/site-packages/gribapi/gribapi.py", line 34, in <module>
    from gribapi.errors import GribInternalError
  File "/tmp/repro/.venv/lib/python3.13/site-packages/gribapi/errors.py", line 16, in <module>
    from .bindings import ENC, ffi, lib
  File "/tmp/repro/.venv/lib/python3.13/site-packages/gribapi/bindings.py", line 105, in <module>
    raise RuntimeError("Cannot find the ecCodes library")
RuntimeError: Cannot find the ecCodes library
```

</p>
</details> 

<details><summary>just cfgrib with Python 3.14</summary>
<p>

```console
➜  ~ docker run -ti --rm ubuntu /bin/bash
root@72b3ca53bce9:/# apt-get update && apt-get install -y curl && curl -LsSf https://astral.sh/uv/install.sh | sh

[truncated for brevity]

downloading uv 0.11.9 x86_64-unknown-linux-gnu
installing to /root/.local/bin
  uv
  uvx
everything's installed!

To add $HOME/.local/bin to your PATH, either restart your shell or run:

    source $HOME/.local/bin/env (sh, bash, zsh)
    source $HOME/.local/bin/env.fish (fish)
root@72b3ca53bce9:/# source $HOME/.local/bin/env
root@72b3ca53bce9:/# mkdir /tmp/repro && cd /tmp/repro && uv init --python 3.14 && uv add cfgrib && uv run python -m eccodes selfcheck
Initialized project `repro`
Using CPython 3.14.4
Creating virtual environment at: .venv
Resolved 12 packages in 1.58s
Prepared 10 packages in 14.42s
Installed 10 packages in 26ms
 + attrs==26.1.0
 + cffi==2.0.0
 + cfgrib==0.9.15.1
 + click==8.3.3
 + eccodes==2.47.0
 + eccodeslib==2.46.2.19
 + eckitlib==2.0.7.19
 + findlibs==0.1.2
 + numpy==2.4.4
 + pycparser==3.0
Found: ecCodes v2.46.2.
Library: /tmp/repro/.venv/lib/python3.14/site-packages/eccodeslib/lib64/libeccodes.so
Definitions: /MEMFS/definitions
Samples: /MEMFS/samples
Your system is ready.
```

</p>
</details> 

### Atlite MRE reproduction
Did you try to reproduce the issue on a clean install of Ubuntu? Below is a short screencast of a reproduction on a clean ubuntu docker container. I observe the same behavior on my Ubuntu install - `eccodeslib` doesn't get installed by default. `uv add eccodeslib` fixes it.

https://github.com/user-attachments/assets/7802bc83-b91c-4ea1-b45a-6c3073d7eaf6



### test.py failing
Again, my bad, apologies, I copy-pasted a wrong test.py inside the reproduction steps, the cutout was missing a path argument. now fixed.

### conclusion
This only applies to a tiny minority of users (people who want to fork atlite and use uv to manage dependencies), so likely not a big deal. But the fix is also super simple.
